# Generated by Django 2.2.7 on 2019-12-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
