# Generated by Django 2.2.7 on 2019-12-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
